"""empty message

Revision ID: 533170990c24
Revises: b7919ce4c4e9
Create Date: 2018-11-19 15:34:59.572964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533170990c24'
down_revision = 'b7919ce4c4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.create_foreign_key(None, 'tournament', 'user', ['creator_id'], ['id'])
    op.drop_column('tournament', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('creator', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.create_foreign_key(None, 'tournament', 'user', ['creator'], ['id'])
    op.drop_column('tournament', 'creator_id')
    # ### end Alembic commands ###
